// C4D-DialogResource
DIALOG DLG_BATCHRENDERPOSTSCRIPT
{
  NAME IDS_DIALOG; SCALE_V; SCALE_H; 
  
  GROUP GRP_ALL
  {
    SCALE_V; SCALE_H; 
    BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP GRP_OPTIONS
    {
      NAME IDS_STATIC12; ALIGN_TOP; SCALE_H; 
      BORDERSIZE 6, 8, 6, 8; 
      ROWS 1;
      SPACE 4, 4;
      
      CHECKBOX CHK_RUNNING { NAME IDS_CHECK2; ALIGN_TOP; SCALE_H;  }
      STATICTEXT STATIC_INFO { NAME IDS_STATIC13; CENTER_V; ALIGN_RIGHT; }
      BUTTON BTN_OPENBR { NAME IDS_BUTTON5; ALIGN_TOP; ALIGN_LEFT; }
    }
    GROUP GRP_SCRIPT
    {
      NAME IDS_STATIC3; SCALE_V; SCALE_H; 
      BORDERSTYLE BORDER_GROUP_TOP; BORDERSIZE 6, 8, 6, 8; 
      COLUMNS 1;
      SPACE 4, 4;
      
      MULTILINEEDIT EDT_SCRIPT
      { 
        SCALE_V; SCALE_H; SIZE 700, 150; 
        MONOSPACED; SYNTAXCOLOR; PYTHON; STATUSBAR; 
      }
      GROUP GRP_SCRIPT_ACTIONS
      {
        NAME IDS_STATIC6; ALIGN_TOP; SCALE_H; 
        BORDERSIZE 0, 4, 2, 0; 
        ROWS 1;
        SPACE 4, 4;
        
        BUTTON BTN_SCRIPT_COMPILE { NAME IDS_BUTTON; ALIGN_TOP; CENTER_H; }
        STATICTEXT STATIC_SCRIPT_INFO { NAME IDS_STATIC11; CENTER_V; SCALE_H; }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC14; CENTER_V; ALIGN_LEFT; }
        USERAREA UA_SCRIPT_COMPILEOK { ALIGN_TOP; ALIGN_RIGHT; SIZE 27, 12; }
      }
    }
  }
}