// C4D-DialogResource
DIALOG DLG_ABOUT
{
  NAME IDS_DIALOG; SCALE_V; SCALE_H; 
  
  GROUP GRP_ALL
  {
    NAME IDS_STATIC; CENTER_V; CENTER_H; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 8, 8, 8, 8; 
    COLUMNS 2;
    
    STATICTEXT IDC_STATIC { NAME IDS_STATIC9; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC10; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC3; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC1; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC2; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC5; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC6; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC7; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC8; CENTER_V; ALIGN_LEFT; }
  }
}